const products = [
  {
    id: 1,
    name: 'Lux Chocolate',
    img: {
      src: '/img/donut-lux-chocolat.jpg',
      width: 2000,
      height: 3000,
      alt: 'Hand-tar-Lux-Chocolate-munk',
    },
    price: 60,
    rating: 4,
    category: 'Donut',
  },

  {
    id: 2,
    name: 'Vanilla',
    img: {
      src: '/img.donut-vanilla.jpg',
      width: 3145,
      height: 4718,
      alt: 'Tre-vanilj-munkar',
    },
    price: 20,
    rating: 4,
    category: 'Donut',
  },
  {
    id: 3,
    name: 'Blueberry',
    img: {
      src: '/img/donut-blueberry.jpg',
      width: 4096,
      height: 2160,
      alt: 'En-blåbärsmunk-med-strössel',
    },
    price: 28,
    rating: 5,
    category: 'Donut',
  },
  {
    id: 4,
    name: 'Honey Swirl',
    img: 'img.jpg',
    price: 38,
    rating: 5,
    category: 'Icecream',
  },
  {
    id: 5,
    name: 'Breezy Melon',
    img: 'img.jpg',
    price: 38,
    rating: 3,
    category: 'Icecream',
  },
  {
    id: 6,
    name: 'Salty Liquorice',
    img: 'img.jpg',
    price: 46,
    rating: 4,
    category: 'Icecream',
  },
  {
    id: 7,
    name: 'Marsmallow',
    img: 'img.jpg',
    price: 50,
    rating: 2,
    category: 'Milkshake',
  },
  {
    id: 8,
    name: 'YUUM special!',
    img: 'img.jpg',
    price: 50,
    rating: 4,
    category: 'Milkshake',
  },
  {
    id: 9,
    name: 'Cocos',
    img: 'img.jpg',
    price: 58,
    rating: 5,
    category: 'Milkshake',
  },
  {
    id: 10,
    name: 'Mango',
    img: 'img.jpg',
    price: 50,
    rating: 5,
    category: 'Milkshake',
  },
];

export default products;
