const products = [
  {
    id: 1,
    name: 'Lux Chocolate',
    img: {
      src: '/fed25d-js-intro-inl-1-Linboe/img/donut-lux-chocolat.jpg',
      width: 2000,
      height: 3000,
      alt: 'Hand-tar-Lux-Chocolate-munk',
    },
    price: 60,
    rating: 4,
    category: 'Donut',
  },

  {
    id: 2,
    name: 'Vanilla',
    img: {
      src: '/fed25d-js-intro-inl-1-Linboe/img/donut-vanilla.jpg',
      width: 3145,
      height: 4718,
      alt: 'Tre-vanilj-munkar',
    },
    price: 20,
    rating: 4,
    category: 'Donut',
  },
  {
    id: 3,
    name: 'Blueberry',
    img: {
      src: '/fed25d-js-intro-inl-1-Linboe/img/donut-blueberry.jpg',
      width: 4096,
      height: 2160,
      alt: 'En-blåbärsmunk-med-strössel',
    },
    price: 28,
    rating: 5,
    category: 'Donut',
  },
  {
    id: 4,
    name: 'Berry Swirl',
    img: {
      src: '/fed25d-js-intro-inl-1-Linboe/img/icecream-berry-swirl.jpg',
      width: 4096,
      height: 2160,
      alt: 'En-glasskon-med-rosa-mjukglass',
    },
    price: 38,
    rating: 5,
    category: 'Icecream',
  },
  {
    id: 5,
    name: 'Salty Liquorice',
    img: {
      src: '/fed25d-js-intro-inl-1-Linboe/img/icecream-salty-liquorice.jpg',
      width: 4096,
      height: 2160,
      alt: 'En-hand-håller-glasskon-med-mjukglass',
    },
    price: 46,
    rating: 4,
    category: 'Icecream',
  },
  {
    id: 6,
    name: 'Soft Honey',
    img: {
      src: '/fed25d-js-intro-inl-1-Linboe/img/icecream-soft-honey.jpg',
      width: 4096,
      height: 2160,
      alt: 'En-person-slickar-mjukglass-i-kon',
    },
    price: 38,
    rating: 3,
    category: 'Icecream',
  },
  {
    id: 7,
    name: 'Marsmallow',
    img: {
      src: '/fed25d-js-intro-inl-1-Linboe/img/milkshake-marsmallow.jpg',
      width: 4096,
      height: 2160,
      alt: 'Ett-högt-glas-med-milkshake-kakor-i-bakgrunden',
    },
    price: 50,
    rating: 2,
    category: 'Milkshake',
  },
  {
    id: 8,
    name: 'Coco',
    img: {
      src: '/fed25d-js-intro-inl-1-Linboe/img/milkshake-coco.jpg',
      width: 4096,
      height: 2160,
      alt: 'Ett-glas-med-milkshake-och-sugrör',
    },
    price: 58,
    rating: 5,
    category: 'Milkshake',
  },
  {
    id: 9,
    name: 'YUUM special!',
    img: {
      src: '/fed25d-js-intro-inl-1-Linboe/img/milkshake-yuum-special.jpg',
      width: 4096,
      height: 2160,
      alt: 'Ett-glas-med-milkshake-toppat-med-grädde-choklad-marsmallows-spiller-ut-på-bordet',
    },
    price: 50,
    rating: 4,
    category: 'Milkshake',
  },
  {
    id: 10,
    name: 'Mango',
    img: {
      src: '/fed25d-js-intro-inl-1-Linboe/img/milkshake-mango.jpg',
      width: 4096,
      height: 2160,
      alt: 'En-glasmugg-med-milkshake-toppat-med-mango',
    },
    price: 50,
    rating: 5,
    category: 'Milkshake',
  },
];

export default products;
