const products = [
  {
    id: 1,
    name: 'Lux Chocolate',
    images: 'img.jpg',
    price: 60,
    rating: 4,
    category: 'Donut',
  },
  {
    id: 2,
    name: 'Vanilla',
    images: 'img.jpg',
    price: 20,
    rating: 4,
    category: 'Donut',
  },
  {
    id: 3,
    name: 'Blueberry',
    images: 'img.jpg',
    price: 28,
    rating: 5,
    category: 'Donut',
  },
  {
    id: 4,
    name: 'Honey Swirl',
    images: 'img.jpg',
    price: 38,
    rating: 5,
    category: 'Icecream',
  },
  {
    id: 5,
    name: 'Breezy Melon',
    images: 'img.jpg',
    price: 38,
    rating: 3,
    category: 'Icecream',
  },
  {
    id: 6,
    name: 'Salty Liquorice',
    images: 'img.jpg',
    price: 46,
    rating: 4,
    category: 'Icecream',
  },
  {
    id: 7,
    name: 'Marsmallow',
    images: 'img.jpg',
    price: 50,
    rating: 2,
    category: 'Milkshake',
  },
  {
    id: 8,
    name: 'YUUM special!',
    images: 'img.jpg',
    price: 50,
    rating: 4,
    category: 'Milkshake',
  },
  {
    id: 9,
    name: 'Cocos',
    images: 'img.jpg',
    price: 58,
    rating: 5,
    category: 'Milkshake',
  },
  {
    id: 10,
    name: 'Mango',
    images: 'img.jpg',
    price: 50,
    rating: 5,
    category: 'Milkshake',
  },
];

export default products;
